=== NotAShelf/notashelf.dev/apps/web/.astro/collections/projects.schema.json
{
  "$ref": "#/definitions/projects",
  "definitions": {
    "projects": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "sourceUrl": {
          "type": "string"
        },
        "startDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date-time"
            },
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "integer",
              "format": "unix-time"
            }
          ]
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        },
        "active": {
          "type": "boolean",
          "default": true
        },
        "featurable": {
          "type": "boolean",
          "default": true
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "sourceUrl"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== NotAShelf/notashelf.dev/apps/notashelf.dev/src/data/projects/hyprkeys.json
{
  "title": "Hyprkeys",
  "description": "Powerful and easy to use keyboard utility designed for my favorite Wayland Compositor, Hyprland.",
  "sourceUrl": "https://github.com/hyprland-community/Hyprkeys",
  "tags": ["Go", "Wayland", "Hyprland", "Utility"],
  "active": false,
  "featurable": false
}

=== NotAShelf/notashelf.dev/apps/notashelf.dev/src/data/projects/notashelf-dev.json
{
  "title": "notashelf.dev",
  "description": "My very own web sandbox, serves as my personal website and blog.",
  "sourceUrl": "https://github.com/notashelf/notashelf.dev",
  "startDate": "2022-06-1",
  "tags": ["astro", "nix", "svelte", "react", "Rust", "WASM", "blog"],
  "active": true,
  "featurable": false
}
